if [ "${_CONDA_SET_PGADMIN4_PY_HOME+x}" ] ; then
  export PGADMIN4_PY_HOME=$_CONDA_SET_PGADMIN4_PY_HOME
  export PGADMIN4_PY_EXEC=$_CONDA_SET_PGADMIN4_PY_EXEC
  unset _CONDA_SET_PGADMIN4_PY_EXEC
  unset _CONDA_SET_PGADMIN4_PY_HOME
fi