context:
  name: pgadmin4-desktop
  version: "9.3"
  yarn_version: "3.8.7"
  electron_version: "34.5.5"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://ftp.postgresql.org/pub/pgadmin/pgadmin4/v${{ version }}/source/pgadmin4-${{ version }}.tar.gz
    sha256: fbeae20038e2bd256e2b9b3a83e65f87b87030ba1b64ba38a15f27ca3e63b681
    patches:
      - patches/set-pgadmin4-path-pgadmin4.js.patch

build:
  skip: ppc64le
  number: 1
  dynamic_linking:
    binary_relocation: ${{ false if osx else true }}

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - curl
    - pnpm
    - yarn ==${{ yarn_version }}
    - if: unix
      then:
        - sed
        - syft
        - unzip
  host:
    - libvulkan-loader
    - pgadmin4-python ==${{ version }}
    - if: linux
      then:
        - ${{ cdt("mesa-libgbm") }}
        - alsa-lib
        - libegl
        - libgles
        - libdrm
        - libglvnd
        - libudev
        - nss
    - if: unix
      then:
        - atk
        - cairo
        - dbus
        - glib
        - gtk3
        - mesalib
        - pango
        - xorg-libx11
        - xorg-libxcomposite
        - xorg-libxext
        - xorg-libxdamage
        - xorg-libxfixes
        - xorg-libxrandr
      else:
        - m2-sed
        - m2-unzip
        - rcedit
  run:
    - libvulkan-loader
    - pgadmin4-python ==${{ version }}
    - if: linux and aarch64
      then:
        - sysroot_linux-aarch64 >=2.28
    - if: linux
      then:
        - alsa-lib
        - fontconfig
        - libdrm
        - libegl
        - libgles
        - libglvnd
        - libxcrypt1
        - mesalib
        - nss
        - xorg-libx11
        - xorg-libxcomposite
        - xorg-libxext
        - xorg-libxdamage
        - xorg-libxfixes
        - xorg-libxrandr
    - if: unix
      then:
        - mesalib

tests:
  - package_contents:
      files:
        - ${{ "Library/" if not unix else "" }}share/icons/hicolor/128x128/apps/pgadmin4.png
        - ${{ "Library/" if not unix else "" }}share/icons/hicolor/16x16/apps/pgadmin4.png
        - ${{ "Library/" if not unix else "" }}share/icons/hicolor/32x32/apps/pgadmin4.png
        - ${{ "Library/" if not unix else "" }}share/icons/hicolor/48x48/apps/pgadmin4.png
        - ${{ "Library/" if not unix else "" }}share/icons/hicolor/64x64/apps/pgadmin4.png

        - ${{ "Library/" if not unix else "" }}Menu/pgadmin4_menu.json
        - if: osx
          then:
            - Menu/pgadmin4.icns
            - usr/pgadmin4.app/Contents/MacOS/pgadmin4
            - usr/pgadmin4.app/Contents/Frameworks/pgAdmin 4 Helper (GPU).app/Contents/MacOS/pgAdmin 4 Helper (GPU)
            - usr/pgadmin4.app/Contents/Frameworks/pgAdmin 4 Helper (Plugin).app/Contents/MacOS/pgAdmin 4 Helper (Plugin)
            - usr/pgadmin4.app/Contents/Frameworks/pgAdmin 4 Helper (Renderer).app/Contents/MacOS/pgAdmin 4 Helper (Renderer)
            - usr/pgadmin4.app/Contents/Frameworks/pgAdmin 4 Helper.app/Contents/MacOS/pgAdmin 4 Helper
            - usr/pgadmin4.app/Contents/Frameworks/Electron Framework.framework/Electron Framework
            - usr/pgadmin4.app/Contents/Frameworks/Electron Framework.framework/Resources/Info.plist
            - usr/pgadmin4.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/Info.plist
            - usr/pgadmin4.app/Contents/Frameworks/Electron Framework.framework/Versions/Current/Electron Framework
            - usr/pgadmin4.app/Contents/Frameworks/Electron Framework.framework/Versions/Current/Resources/Info.plist
            - usr/pgadmin4.app/Contents/Resources/app/assets/pgAdmin4.png
            - usr/pgadmin4.app/Contents/Resources/pgAdmin4.icns
            # This seems to need to be linked post-installation
            # - usr/pgadmin4.app/Contents/Resources/web/pgAdmin4.py
          else:
            - ${{ "Library/" if not unix else "" }}usr/pgadmin4/bin/resources/app/assets/*
            - ${{ "Library/" if not unix else "" }}usr/pgadmin4/bin/resources/app/node_modules/*
            - ${{ "Library/" if not unix else "" }}usr/pgadmin4/bin/resources/app/package.json
            - ${{ "Library/" if not unix else "" }}usr/pgadmin4/bin/resources/app/src/*
        - if: linux
          then:
            - Menu/pgadmin4.png
            - usr/pgadmin4/bin/pgadmin4
        - if: not unix
          then:
            - Library/Menu/pgadmin4.ico
            - Library/usr/pgadmin4/bin/pgadmin4.exe
  - script:
      - if: unix
        then:
          - if: linux or (osx and x86_64)
            then: cd testing && export HEADLESS=true && python run_pgadmin4.py
          - if: osx and arm64
            then:
              - otool -hv ${PREFIX}/usr/pgadmin4.app/Contents/MacOS/pgadmin4
        else:
          - cd testing
          - set HEADLESS=true
          -
          - python run_pgadmin4.py
    files:
      recipe:
        - testing/
    requirements:
      run:
        - python

about:
  homepage: https://github.com/pgadmin-org/pgadmin4
  summary: 'pgAdmin 4 Desktop application'
  description: |
    pgAdmin is the most popular and feature rich Open Source administration and
    development platform for PostgreSQL, the most advanced Open Source database in the world.
  license: PostgreSQL
  license_file:
    - LICENSE
  documentation: https://www.pgadmin.org/
  repository: https://github.com/pgadmin-org/pgadmin4

extra:
  recipe-maintainers:
    - MementoRC
